apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: ghcr.io/siva-828926/bad-court:35da0d05196b83f31d98eef0839984c4c7cb85bf
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /badcourt/actuator/health
            port: 8080
          initialDelaySeconds: 100
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /badcourt/actuator/health
            port: 8080
          initialDelaySeconds: 200
          periodSeconds: 3