apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: ghcr.io/siva-828926/bad-court:24c840d48965a4e5b1372044b535f2f1fe2d2e19
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /badcourt/actuator/health
            port: 8080
          initialDelaySeconds: 30ss
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /badcourt/actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 3